
def draw_hangman(difficulty_level, remaining_guesses):
    """This function draws the different parts of the Hangman. 
    
    It is contingent upon the number of guesses remaining and the difficulty level the user selected.
    """

    if ((remaining_guesses == 6 and difficulty_level == 1) or (remaining_guesses == 5 and difficulty_level == 2) or (remaining_guesses == 4 and difficulty_level == 3)):
        print("*************")
        print("*")
        print("*")
        print("*")
        print("*")
        print("*")
        print("*")
        print("*")         
        print("*")
        print("*")
        print("*")
        print("*")
        print("*") 
        print("*")
        print("*") 
        print("*")
        print("*************")
        
    elif remaining_guesses == 5 and difficulty_level == 1:
            print("*************")
            print("*          *")
            print("*          *")
            print("*          *")
            print("*          0")
            print("*        0   0")
            print("*          0")
            print("*")
            print("*")
            print("*")
            print("*")
            print("*") 
            print("*")
            print("*") 
            print("*")
            print("*************")

    elif ((remaining_guesses == 4 and difficulty_level == 1 or difficulty_level == 2) or (remaining_guesses == 3 and difficulty_level == 3)):
            print("*************")
            print("*          *")
            print("*          *")
            print("*          *")
            print("*          0")
            print("*        0   0")
            print("*          0")
            print("*          |")
            print("*          |")
            print("*          |")
            print("*          |")
            print("*          |") 
            print("*")
            print("*") 
            print("*")
            print("*************")

    elif (remaining_guesses == 3 and difficulty_level == 1 or difficulty_level == 2):
            print("*************")
            print("*          *")
            print("*          *")
            print("*          *")
            print("*          0")
            print("*        0   0")
            print("*          0")
            print("*          |")
            print("*          |")
            print("*      --- |")
            print("*          |")
            print("*          |") 
            print("*")
            print("*") 
            print("*")
            print("*************")

    elif remaining_guesses == 2:
            print("*************")
            print("*          *")
            print("*          *")
            print("*          *")
            print("*          0")
            print("*        0   0")
            print("*          0")
            print("*          |")
            print("*          |")
            print("*      --- |---")
            print("*          |")
            print("*          |") 
            print("*")
            print("*") 
            print("*")
            print("*************")

    elif remaining_guesses == 1:
            print("*************")
            print("*          *")
            print("*          *")
            print("*          *")
            print("*          0")
            print("*        0   0")
            print("*          0")
            print("*          |")
            print("*          |")
            print("*      --- |---")
            print("*          |")
            print("*          |") 
            print("*         /")
            print("*        /") 
            print("*")
            print("*************")

    elif remaining_guesses == 0:         
            print("*************")
            print("*          *")
            print("*          *")
            print("*          *")
            print("*          0")
            print("*        0   0")
            print("*          0")
            print("*          | ")         
            print("*          |")
            print("*       ---|---")
            print("*          |")
            print("*          |")
            print("*         / \ ") 
            print("*        /   \ ")
            print("*") 
            print("*")
            print("*************")
